### ISSUE TITLE
Audible BEEP when switching presets 

### ISSUE THREAD

**Issue by Sedaxel** [mikeoliphant/stompbox-old#2]
When switching presets, sometimes an audible BEEP sounds briefly. It's no more than half a second long.

In my case, it occurs when being in a preset containing a hi-gain NAM model and switching to a preset containing a clean NAM model. It doesn't happen the other way around, nor switching between clean NAM presets.

**Comment by mikeoliphant** [comment]
I've added a 50ms audio ramp down/up before/after preset loading and made the actual preset loading happen on a background thread. This should avoid any audio discontinuities due to preset loading.

**Comment by Sedaxel** [comment]
It works perfectly now! No beep at all. Thank you!

**Comment by mikeoliphant** [comment]
👍
